### ISSUE TITLE
Link from homepage broken

### ISSUE THREAD

**Issue by tommorris** [DeterminateSystems/flakehub-docs#7]
On [flakehub.com](https://flakehub.com/), there is a link titled "Why should I publish my flake?"

It points to `https://flakehub.com/docs/#why-should-i` which does not answer the question "why should I publish my flake?"

It should probably point to `https://flakehub.com/docs/faq#why-publish` which does.

**Comment by lucperkins** [comment]
At some point along the line I fixed this 😄
